//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKSApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lksEntities : DbContext
    {
        public lksEntities()
            : base("name=lksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblbarang> tblbarangs { get; set; }
        public virtual DbSet<tbldetail> tbldetails { get; set; }
        public virtual DbSet<tbllog> tbllogs { get; set; }
        public virtual DbSet<tbltran> tbltrans { get; set; }
        public virtual DbSet<tbluser> tblusers { get; set; }
    }
}
