//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbarang
    {
        public string idbarang { get; set; }
        public string kode { get; set; }
        public string nama { get; set; }
        public Nullable<System.DateTime> exp { get; set; }
        public Nullable<long> jumlah { get; set; }
        public string satuan { get; set; }
        public Nullable<long> harga { get; set; }
        public string gambar { get; set; }
    }
}
