//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldetail
    {
        public int iddetail { get; set; }
        public string namabarang { get; set; }
        public Nullable<long> jumlahbarang { get; set; }
        public string idbarang { get; set; }
        public string idtrans { get; set; }
    }
}
