//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbllog
    {
        public int idlog { get; set; }
        public Nullable<System.DateTime> waktu { get; set; }
        public string aktivitas { get; set; }
        public Nullable<int> iduser { get; set; }
    }
}
