//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltran
    {
        public string idtrans { get; set; }
        public string notrans { get; set; }
        public Nullable<System.DateTime> tgltrans { get; set; }
        public Nullable<long> total { get; set; }
        public Nullable<int> iduser { get; set; }
    }
}
