//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbluser
    {
        public int iduser { get; set; }
        public string tipe { get; set; }
        public string nama { get; set; }
        public string alamat { get; set; }
        public string telp { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public string gambar { get; set; }
    }
}
